# Environment variables
set -x PGGSSENCMODE disable

set -x HOMEBREW_NO_AUTO_UPDATE 1
set -x HOMEBREW_NO_ENV_HINTS 1
set -x HOMEBREW_NO_EMOJI 1
set -x HOMEBREW_NO_INSTALL_CLEANUP 1
set -x HOMEBREW_NO_ANALYTICS 1
set -x HOMEBREW_API_AUTO_UPDATE_SECS 86400
